#!/usr/bin/env bash
# harness/antigravity.sh — install fleet into Antigravity (agy CLI + desktop).
# Skills -> ~/.gemini/antigravity/global_skills (the dir agy reads fleet-wide).
# MCPs -> `agy mcp add` (agy's own registry; per-tool defs are generated by agy).
set -u
AF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../lib/common.sh
source "$AF_DIR/lib/common.sh"

af_have agy || { af_skip "antigravity: agy not installed"; exit 0; }
command -v rsync >/dev/null || af_die "rsync required"

AG_SKILLS="$HOME/.gemini/antigravity/global_skills"
AG_CONFIG_SKILLS="$HOME/.gemini/config/skills"

# ---- skills -----------------------------------------------------------------
# Antigravity discovers flat skills: <global>/<name>/SKILL.md. Current documented
# global dir is ~/.gemini/config/skills; the older ~/.gemini/antigravity/global_skills
# is kept in sync as a compatibility copy. Stage a flat copy of the categorised tree.
stage="$(mktemp -d)"
for d in "$AF_DIR"/skills/*/; do
  [ -f "$d/SKILL.md" ] || continue
  cp -a "$d" "$stage/$(basename "$d")"
done
dupes=""
for d in "$AF_DIR"/skills/*/*/; do
  [ -f "$d/SKILL.md" ] || continue
  n="$(basename "$d")"
  if [ -e "$stage/$n" ]; then dupes="$dupes $n"; continue; fi
  cp -a "$d" "$stage/$n"
done
[ -n "$dupes" ] && af_warn "duplicate skill names, first copy kept:$dupes"
af_run "install flat skills -> $AG_CONFIG_SKILLS" rsync -a --delete "$stage/" "$AG_CONFIG_SKILLS/"
af_run "install flat skills -> $AG_SKILLS" rsync -a --delete "$stage/" "$AG_SKILLS/"
rm -rf "$stage"

# ---- MCPs (same set as the claude leg) -------------------------------------
agy_mcp_present() { agy mcp list 2>/dev/null | grep -q "^$1\b\|^$1 "; }

tmpi="$(mktemp)"; tmps="$(mktemp)"; echo "[]" > "$tmpi"; echo "[]" > "$tmps"
add_json() { python3 -c 'import json,sys; l=json.load(open(sys.argv[1])); l.append(sys.argv[2]); json.dump(l, open(sys.argv[1],"w"))' "$1" "$2"; }

# name|kind|spec|args|ENV_NAMES|notes   (same rows as mcp/claude.list)
while IFS='|' read -r name kind spec args envs notes; do
  [ -z "$name" ] && continue
  case "$name" in \#*) continue ;; esac

  skip=""
  if [ -n "$envs" ]; then
    IFS=',' read -ra KEYS <<< "$envs"
    for k in "${KEYS[@]}"; do
      [ -z "$k" ] && continue
      if [ -z "$(af_env_get "$k")" ]; then
        af_prompt_key "$k" "antigravity MCP $name"
        rc=$?
        if [ $rc -eq 2 ]; then
          af_skip "$name: env key $k not provided"
          add_json "$tmps" "$name (env key $k not provided)"
          skip=1; break
        fi
      fi
    done
  fi
  [ -n "$skip" ] && continue

  if agy_mcp_present "$name"; then af_log "$name already in agy (skip)"; add_json "$tmpi" "$name (already present)"; continue; fi

  if [ "$kind" = "http" ]; then
    af_run "agy mcp add $name (http)" \
      agy mcp add --type http "$name" "$spec"
  else
    # shellcheck disable=SC2086
    af_run "agy mcp add $name (stdio)" \
      agy mcp add --type stdio "$name" "$spec" $args
  fi
  add_json "$tmpi" "$name"
done < "$AF_DIR/mcp/claude.list"

af_manifest antigravity_installed "$(cat "$tmpi")"
af_manifest antigravity_skipped "$(cat "$tmps")"
rm -f "$tmpi" "$tmps"

skillcount="$(find "$AG_SKILLS" -name SKILL.md 2>/dev/null | wc -l)"
af_manifest antigravity_skills "$skillcount"
af_ok "antigravity leg done (skills: $skillcount)"
